# Generated by Django 3.0 on 2021-01-25 15:47

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20210125_2104'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='date_of_birth',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 25, 15, 47, 0, 577787, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
